# Logging
verbose           : True
log_file_basename : 20170714

# Input files
mc            :     False
directory     :     /data/datasets/CTA/DATA/FULLSEQ/

# Output file
output_directory  : /data/datasets/CTA/DATA/FULLSEQ/

# Camera Configuration
angle_cts         : 0.

# Base definition for the signal extraction
window_width      : 7
window_start      : 3
charge_extraction : integration_saturation

# Event processing
baseline_per_event_limit : 50
n_samples : 92